name: Release and Publish NuGet

on:
  push:
    tags:
      - "v*"  # Asegúrate de usar etiquetas como vG20220001

jobs:
  release-nuget:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Pack NuGet
      run: dotnet pack Math.Lib/Math.Lib.csproj -c Release -o out /p:PackageVersion=${GITHUB_REF##*/v}

    - name: Publish to GitHub Packages
      run: dotnet nuget push "out/*.nupkg" --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Publicación automática del paquete NuGet con versión de matrícula.
