name: Release NuGet

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-pack-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore MyMath/MyMath.sln

      - name: Build solution
        run: dotnet build MyMath/MyMath.sln --configuration Release --no-restore

      - name: Pack NuGet
        run: |
          dotnet pack MyMath/Math.Lib/Math.Lib.csproj --configuration Release --output nupkgs /p:PackageVersion=2022.0742.61

      - name: Publish NuGet to GitHub Packages
        run: |
          dotnet nuget push nupkgs/*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: nupkgs/*.nupkg